name: "config"
description: "write app.config.json file"
inputs:
  branch: # id of input
    description: "name of branch"
    required: true
outputs:
  config: # id of output
    description: "config json"
runs:
  using: "node12"
  main: "dist/index.js"
