name: "config"
description: "write app.config.json file"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
  branch: # id of input
    description: "name of branch"
    required: true
    default: "..."
outputs:
  time: # id of output
    description: "The time we greeted you"
  appconfig: # id of output
    description: "app config json"
runs:
  using: "node12"
  main: "dist/index.js"
