name: "config"
description: "write app.config.json file"
inputs:
  branch: # github.ref_name
    description: "name of branch"
    required: true
  hash: # github.sha
    description: "hash of last commit"
    required: true
outputs:
  config: # id of output
    description: "config json"
runs:
  using: "node12"
  main: "dist/index.js"
